import { getProducts } from "@/redux/product/action";
import { stateType } from "@/redux/product/reducer";
import { storeType, rootReducerType } from "@/redux/store";
import { SimpleGrid } from "@mantine/core";
import ProductCard from "components/ProductCard";
import Head from "next/head";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";

export default function Home() {
	const { loading, error, data } = useSelector<storeType, stateType>(
		(store) => store.product,
	);
	
	const dispatch = useDispatch();
  useEffect(()=>{
	dispatch(getProducts());
  },[dispatch])

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<SimpleGrid cols={3}  spacing={'xl'}>
					{data.length && data.map((product)=><ProductCard key={product.id} product={product} />)}
				</SimpleGrid>
				
			</main>
		</>
	);
}
